apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml
  - app.yaml
  - ratelimitpolicy.yaml

patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1beta1
      kind: HTTPRoute
      name: petstore-route
      namespace: petstore
    path: httproute-patch.yaml
