apiVersion: v1
kind: Namespace
metadata:
  name: petstore
---
apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: petstore
spec:
  ports:
    - name: http-port
      port: 8080
      targetPort: http-port
      protocol: TCP
  selector:
    app: petstore     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore
  namespace: petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
      - name: petstore
        image: quay.io/kuadrant/petstore3:1.0.0
        imagePullPolicy: Always
        ports:
          - name: http-port
            containerPort: 8080
            protocol: TCP
        volumeMounts:
        - name: log-volume
          mountPath: /var/log
      volumes:
      - name: log-volume
        emptyDir:
          medium: Memory
          sizeLimit: "64Mi"
---
apiVersion: kuadrant.io/v1beta2
kind: RateLimitPolicy
metadata:
  name: petstore
  namespace: petstore
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: petstore-route
  limits:
    "login":
      rates:
      - limit: 3
        duration: 10
        unit: second
      routeSelectors:
      - matches:
        - method: GET
          path:
            type: PathPrefix
            value: "/api/v3/user/login"
