apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petstore

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: cluster-config
  literals:
  - REGION=eu