apiVersion: v1
kind: ConfigMap
metadata:
  name: placement
  namespace: argocd
data:
  # apiVersion of the target resource
  apiVersion: cluster.open-cluster-management.io/v1beta1
  # kind of the target resource
  kind: placementdecisions
  # status key name that holds the list of Argo CD clusters
  statusListKey: decisions
  # The key in the status list whose value is the cluster name found in Argo CD
  matchKey: clusterName

