name: ci 
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.13.1'
      - name: Install YQ
        uses: dcarbone/install-yq-action@v1.1.1
      - run: go version
      - run: go install github.com/kuadrant/kuadrantctl@httproute-kuadrant-extensions
      - run: kuadrantctl version
      - run: kuadrantctl generate kuadrant ratelimitpolicy --oas src/main/resources/openapi.yaml | yq -P > resources/ratelimitpolicy.yaml
      - run: kuadrantctl generate gatewayapi httproute --oas src/main/resources/openapi.yaml | yq -P > resources/httproute.yaml
      # - name: 'Kustomize Build'
      #   uses: karancode/kustomize-github-action@master
      #   with:
      #     kustomize_version: '4.5.4'
      #     kustomize_build_dir: 'resources'
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            resources/ratelimitpolicy.yaml
            resources/httproute.yaml
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}